Rails.application.config.middleware.use OmniAuth::Builder do
  
  #local settings
  provider :foursquare, 'TCFS1BWFBH3RGGMO4K4LJXA5IKGMR5US1ENWONMQCHNDG2FL', 'FOXBJTV2HQF0H4HUT0H2VDY5VYK4HMG0NGXEJGJ2RDQVDWN5'
  
  #Heroku Settings
  #provider :foursquare, 'POEVKANIIU4FGCSWEREYYIYDNWDPKUD3RRLO3ZPQRTHL5LMA', 'EWJUTC1TLCZHTTGR5UN21WFIK2H4KBA1NIBQAK5DKW3KFYCD'
  
end